In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn  as sns
%matplotlib inline

from sklearn import datasets



In [3]:
df_cutting=pd.read_csv('digitization_bind.csv')

In [4]:
df_cutting.head(2)

rank      mname director       provider        date country  n_scrn  \
0    1         명량      김한민      씨제이이앤엠(주)  2014-07-30      한국    1587   
1    2  신과함께-죄와 벌      김용화  롯데쇼핑㈜롯데엔터테인먼트  2017-12-20      한국    1912   

      guest genre    rating       ...        director_score director_grade  \
0  17613682    사극  15세이상관람가       ...             19.946685              a   
1  14410931   판타지  12세이상관람가       ...             16.502886              b   

   actor_score actor_grade  grene_score grene_grade  provider1_power  \
0    12.387048           a     3.336487           d         16.58469   
1     9.926734           c     1.604410         NaN         11.42832   

  providera_grade provider2_power providerb_grade  
0               a        16.58469               a  
1               a        11.42832               a  

[2 rows x 22 columns]

In [5]:
df_cutting_hi = pd.DataFrame([df_cutting.director_grade, df_cutting.actor_grade,df_cutting.grene_grade,df_cutting.providera_grade])

In [6]:
df_cuttingt = df_cutting_hi.T

In [7]:
hi =pd.get_dummies(df_cuttingt, prefix=['director_grade', 'actor_grade', 'grene_grade','providera_grade'])

In [8]:
hi = hi.drop(['director_grade_ ','providera_grade_0','providera_grade_Na'],axis=1)

In [9]:
hi.head()

director_grade_a  director_grade_b  director_grade_c  director_grade_d  \
0                 1                 0                 0                 0   
1                 0                 1                 0                 0   
2                 0                 0                 1                 0   
3                 1                 0                 0                 0   
4                 1                 0                 0                 0   

   director_grade_e  actor_grade_a  actor_grade_b  actor_grade_c  \
0                 0              1              0              0   
1                 0              0              0              1   
2                 0              1              0              0   
3                 0              1              0              0   
4                 0              0              1              0   

   actor_grade_d  grene_grade_a        ...          grene_grade_c  \
0              0              0        ...                      0   
1              0              0        ...                      0   
2              0              0        ...                      1   
3              0              0        ...                      0   
4              0              0        ...                      0   

   grene_grade_d  grene_grade_e  grene_grade_f  grene_grade_g  \
0              1              0              0              0   
1              0              0              0              0   
2              0              0              0              0   
3              0              1              0              0   
4              0              0              0              0   

   providera_grade_a  providera_grade_b  providera_grade_c  providera_grade_d  \
0                  1                  0                  0                  0   
1                  1                  0                  0                  0   
2                  1                  0                  0                  0   
3                  1                  0                  0                  0   
4                  1                  0                  0                  0   

   providera_grade_e  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  

[5 rows x 21 columns]

In [227]:
hi.indexs = range(len(hi))

C:\Users\Jin1ib\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.


In [10]:
hi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1730 entries, 0 to 1729
Data columns (total 21 columns):
director_grade_a     1730 non-null uint8
director_grade_b     1730 non-null uint8
director_grade_c     1730 non-null uint8
director_grade_d     1730 non-null uint8
director_grade_e     1730 non-null uint8
actor_grade_a        1730 non-null uint8
actor_grade_b        1730 non-null uint8
actor_grade_c        1730 non-null uint8
actor_grade_d        1730 non-null uint8
grene_grade_a        1730 non-null uint8
grene_grade_b        1730 non-null uint8
grene_grade_c        1730 non-null uint8
grene_grade_d        1730 non-null uint8
grene_grade_e        1730 non-null uint8
grene_grade_f        1730 non-null uint8
grene_grade_g        1730 non-null uint8
providera_grade_a    1730 non-null uint8
providera_grade_b    1730 non-null uint8
providera_grade_c    1730 non-null uint8
providera_grade_d    1730 non-null uint8
providera_grade_e    1730 non-null uint8
dtypes: uint8(21)
memory usage: 

## 이제 우리가 랜덤포레스트를 돌려볼겁니다.
#### 우선 test set을 돌려보도록 하죠

In [21]:
from sklearn.model_selection import train_test_split

In [11]:
df_cutting.head(0)

Empty DataFrame
Columns: [rank, mname, director, provider, date, country, n_scrn, guest, genre, rating, grade, actor, director_score, director_grade, actor_score, actor_grade, grene_score, grene_grade, provider1_power, providera_grade, provider2_power, providerb_grade]
Index: []

[0 rows x 22 columns]

In [16]:
abx = pd.concat([pd.DataFrame(df_cutting.guest),pd.DataFrame(df_cutting.n_scrn),pd.DataFrame(df_cutting.grade),hi],axis=1)

In [17]:
abx.head()

guest  n_scrn  grade  director_grade_a  director_grade_b  \
0  17613682    1587   8.47                 1                 0   
1  14410931    1912   7.85                 0                 1   
2  14245998     966   9.01                 0                 0   
3  13395400    1064   9.01                 1                 0   
4  12983330    1072   7.60                 1                 0   

   director_grade_c  director_grade_d  director_grade_e  actor_grade_a  \
0                 0                 0                 0              1   
1                 0                 0                 0              0   
2                 1                 0                 0              1   
3                 0                 0                 0              1   
4                 0                 0                 0              0   

   actor_grade_b        ...          grene_grade_c  grene_grade_d  \
0              0        ...                      0              1   
1              0        ...                      0              0   
2              0        ...                      1              0   
3              0        ...                      0              0   
4              1        ...                      0              0   

   grene_grade_e  grene_grade_f  grene_grade_g  providera_grade_a  \
0              0              0              0                  1   
1              0              0              0                  1   
2              0              0              0                  1   
3              1              0              0                  1   
4              0              0              0                  1   

   providera_grade_b  providera_grade_c  providera_grade_d  providera_grade_e  
0                  0                  0                  0                  0  
1                  0                  0                  0                  0  
2                  0                  0                  0                  0  
3                  0                  0                  0                  0  
4                  0                  0                  0                  0  

[5 rows x 24 columns]

In [18]:
X = abx[['n_scrn','grade','director_grade_a','director_grade_b','director_grade_c','director_grade_d','director_grade_e','actor_grade_a','actor_grade_b','actor_grade_c','actor_grade_d','grene_grade_a','grene_grade_b','grene_grade_c','grene_grade_d','grene_grade_e','grene_grade_f','grene_grade_g','providera_grade_a','providera_grade_b','providera_grade_c','providera_grade_d','providera_grade_e']]
y = abx['guest']

In [19]:
abx.head()

guest  n_scrn  grade  director_grade_a  director_grade_b  \
0  17613682    1587   8.47                 1                 0   
1  14410931    1912   7.85                 0                 1   
2  14245998     966   9.01                 0                 0   
3  13395400    1064   9.01                 1                 0   
4  12983330    1072   7.60                 1                 0   

   director_grade_c  director_grade_d  director_grade_e  actor_grade_a  \
0                 0                 0                 0              1   
1                 0                 0                 0              0   
2                 1                 0                 0              1   
3                 0                 0                 0              1   
4                 0                 0                 0              0   

   actor_grade_b        ...          grene_grade_c  grene_grade_d  \
0              0        ...                      0              1   
1              0        ...                      0              0   
2              0        ...                      1              0   
3              0        ...                      0              0   
4              1        ...                      0              0   

   grene_grade_e  grene_grade_f  grene_grade_g  providera_grade_a  \
0              0              0              0                  1   
1              0              0              0                  1   
2              0              0              0                  1   
3              1              0              0                  1   
4              0              0              0                  1   

   providera_grade_b  providera_grade_c  providera_grade_d  providera_grade_e  
0                  0                  0                  0                  0  
1                  0                  0                  0                  0  
2                  0                  0                  0                  0  
3                  0                  0                  0                  0  
4                  0                  0                  0                  0  

[5 rows x 24 columns]

In [20]:
X_train = train

NameError: name 'train' is not defined

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

In [23]:
from sklearn.tree import DecisionTreeClassifier

In [155]:
dtree = DecisionTreeClassifier()

In [156]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [70]:
############# Predictions and Evaluation of Decision Tree


In [24]:
predictions = dtree.predict(X_test) # X_test에 대한 예상치를 predictions에 저장한다.

NameError: name 'dtree' is not defined

In [158]:
from sklearn.metrics import classification_report,confusion_matrix

In [171]:
print(classification_report(y_test,predictions)) # 분류보고서를 y_test와 예상치를 비교
# 0.74 = > 74%의 정확도를 의미한다.

             precision    recall  f1-score   support

       8873       0.00      0.00      0.00         0
       9121       0.00      0.00      0.00         1
       9162       0.00      0.00      0.00         1
       9233       0.00      0.00      0.00         0
       9265       0.00      0.00      0.00         0
       9341       0.00      0.00      0.00         1
       9469       0.00      0.00      0.00         1
       9483       0.00      0.00      0.00         1
       9533       0.00      0.00      0.00         1
       9579       0.00      0.00      0.00         0
       9593       0.00      0.00      0.00         1
       9620       0.00      0.00      0.00         1
       9710       0.00      0.00      0.00         0
       9717       0.00      0.00      0.00         0
       9732       0.00      0.00      0.00         1
       9851       0.00      0.00      0.00         0
      10031       0.00      0.00      0.00         1
      10141       0.00      0.00      0.00   

C:\Users\Jin1ib\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Jin1ib\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [76]:
print("오차 행렬:\n{}".format(confusion_matrix(y_test,predictions)))

오차 행렬:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [25]:
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics

In [26]:
rfc = RandomForestRegressor(n_estimators=100,
                              n_jobs=-1,
                              random_state=0,
                           max_depth=2)

In [27]:
rfc.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=2,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [29]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1211 entries, 1279 to 863
Data columns (total 23 columns):
n_scrn               1211 non-null int64
grade                1211 non-null float64
director_grade_a     1211 non-null uint8
director_grade_b     1211 non-null uint8
director_grade_c     1211 non-null uint8
director_grade_d     1211 non-null uint8
director_grade_e     1211 non-null uint8
actor_grade_a        1211 non-null uint8
actor_grade_b        1211 non-null uint8
actor_grade_c        1211 non-null uint8
actor_grade_d        1211 non-null uint8
grene_grade_a        1211 non-null uint8
grene_grade_b        1211 non-null uint8
grene_grade_c        1211 non-null uint8
grene_grade_d        1211 non-null uint8
grene_grade_e        1211 non-null uint8
grene_grade_f        1211 non-null uint8
grene_grade_g        1211 non-null uint8
providera_grade_a    1211 non-null uint8
providera_grade_b    1211 non-null uint8
providera_grade_c    1211 non-null uint8
providera_grade_d    1211 no

In [40]:
print(rfc.predict([[1605, # 스크린수
                    9.33, # 평점
                    0, 0, 1, 0, 0, # 감독파워
                    0, 1, 0, 0,    # 배우파워
                    0, 1, 0, 0, 0, 0, 0, # 장르파워
                    1, 0, 0, 0, 0  # 배급사파워
                   ]]))

[4765513.48404301]


In [28]:
preds = rfc.predict(X_test)
print('MAE:', metrics.mean_absolute_error(y_test, preds))
print('MSE:', metrics.mean_squared_error(y_test, preds))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, preds)))

MAE: 548103.7690294113
MSE: 1702746758295.5076
RMSE: 1304893.3896282513


In [172]:
print('accuracy:', metrics.accuracy_score(y_test,preds))

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

In [130]:
from sklearn.metrics import classification_report,confusion_matrix

In [131]:
print(classification_report(y_test,predictions))

ValueError: Mix type of y not allowed, got types {'continuous', 'multiclass'}

In [85]:
print(confusion_matrix(y_test,predictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
